SET ECHO ON
SPOOL script/resultats/delete.out

PROMPT Contenu des tables
DELETE FROM DOSSIERPATIENT;
DELETE FROM DOCTEUR;
DELETE FROM CONSULTATION;
DELETE FROM ORDONNANCECHIRURGIE;
DELETE FROM ORDONNANCEMEDICAMENTS;
DELETE FROM ORDONNANCE;
DELETE FROM CHIRURGIE;
DELETE FROM SPECIALISATIONSALLE;
DELETE FROM SALLE;
DELETE FROM TYPECHIRURGIE;
DELETE FROM MEDICAMENT;
DELETE FROM SPECIALITE;
DELETE FROM CATEGORIES;

COMMIT;

SPOOL OFF;