SET ECHO ON
SPOOL script/resultats/drop.out

Prompt Suppression des séquences
DROP SEQUENCE SEQUENCE_MED;
DROP SEQUENCE SEQUENCE_SALLE;
DROP SEQUENCE SEQUENCE_NUMDOS;
DROP SEQUENCE SEQUENCE_CHIRURGIE;
DROP SEQUENCE SEQUENCE_TYPECHIR;
DROP SEQUENCE SEQUENCE_CATMED;
DROP SEQUENCE SEQUENCE_NUMORD;

Prompt Suppression des tables
DROP TABLE DOCTEUR CASCADE CONSTRAINTS;
DROP TABLE CONSULTATION CASCADE CONSTRAINTS;
DROP TABLE ORDONNANCECHIRURGIE;
DROP TABLE CHIRURGIE;
DROP TABLE SPECIALISATIONSALLE;
DROP TABLE ORDONNANCEMEDICAMENTS;
DROP TABLE MEDICAMENT;
DROP TABLE TYPECHIRURGIE;
DROP TABLE SALLE;
DROP TABLE CATEGORIES;
DROP TABLE ORDONNANCE;
DROP TABLE DOSSIERPATIENT CASCADE CONSTRAINTS;
DROP TABLE SPECIALITE;

Prompt Suppression des vues
DROP VIEW NB_CONS_DOCTEUR;
DROP VIEW NB_CHIRURGIE_DOCTEUR;
DROP VIEW NB_CONS_AN;
DROP VIEW NB_CONS_MOY_MOIS;
DROP VIEW NB_CONS_SPECIALITE;
DROP VIEW NB_MED_DOCTEUR;
DROP VIEW NB_MED_DOCTEUR_AN;

COMMIT;
SPOOL OFF;