SET ECHO ON
SPOOL script/resultats/select.out

Prompt Format de la date
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';


PROMPT Contenu des tables
SELECT * FROM DOSSIERPATIENT;
SELECT * FROM DOCTEUR;
SELECT * FROM CONSULTATION;
SELECT * FROM ORDONNANCE;
SELECT * FROM ORDONNANCECHIRURGIE;
SELECT * FROM CHIRURGIE;
SELECT * FROM SALLE;
SELECT * FROM SPECIALISATIONSALLE;
SELECT * FROM TYPECHIRURGIE;
SELECT * FROM ORDONNANCEMEDICAMENTS;
SELECT * FROM MEDICAMENT;
SELECT * FROM SPECIALITE;
SELECT * FROM CATEGORIES;

PROMPT Contenu des vues
SELECT * FROM NB_CONS_DOCTEUR;
SELECT * FROM NB_CHIRURGIE_DOCTEUR;
SELECT * FROM NB_CONS_SPECIALITE;
SELECT * FROM NB_CONS_AN;
SELECT * FROM NB_CONS_MOY_MOIS;
SELECT * FROM NB_MED_DOCTEUR;
SELECT * FROM NB_MED_DOCTEUR_AN;

SPOOL OFF;