package entite;
// Generated 16 avr. 2018 17:18:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "salle_generator")
    @SequenceGenerator(name = "salle_generator", sequenceName = "SEQUENCE_CATMED")
    @Column(name = "idcategorie", updatable = false, nullable = false, unique = true)

    private BigDecimal idcategorie;
    private String nom;
    private String description;
    private Set medicaments = new HashSet(0);

    public Categories() {
    }

    public Categories(BigDecimal idcategorie, String nom) {
        this.idcategorie = idcategorie;
        this.nom = nom;
    }

    public Categories(String nom) {
        this.nom = nom;
    }

    public Categories(BigDecimal idcategorie, String nom, String description, Set medicaments) {
        this.idcategorie = idcategorie;
        this.nom = nom;
        this.description = description;
        this.medicaments = medicaments;
    }

    public BigDecimal getIdcategorie() {
        return this.idcategorie;
    }

    public void setIdcategorie(BigDecimal idcategorie) {
        this.idcategorie = idcategorie;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getMedicaments() {
        return this.medicaments;
    }

    public void setMedicaments(Set medicaments) {
        this.medicaments = medicaments;
    }

}
