package entite;
// Generated 16 avr. 2018 17:18:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Ordonnance generated by hbm2java
 */
public class Ordonnance implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "salle_generator")
    @SequenceGenerator(name = "salle_generator", sequenceName = "SEQUENCE_NUMORD")
    @Column(name = "numord", updatable = false, nullable = false, unique = true)

    private BigDecimal numord;
    private String recommandations;
    private String type;
    private Date datec;
    private Set consultations = new HashSet(0);
    private Set ordonnancechirurgies = new HashSet(0);
    private Set ordonnancemedicamentses = new HashSet(0);

    public Ordonnance() {
    }

    public Ordonnance(BigDecimal numord, String type, Date datec) {
        this.numord = numord;
        this.type = type;
        this.datec = datec;
    }

    public Ordonnance(String type, Date datec) {
        this.type = type;
        this.datec = datec;
    }

    public Ordonnance(String recommandations, String type, Date datec) {
        this.recommandations = recommandations;
        this.type = type;
        this.datec = datec;
    }

    public Ordonnance(BigDecimal numord, String recommandations, String type, Date datec, Set consultations, Set ordonnancechirurgies, Set ordonnancemedicamentses) {
        this.numord = numord;
        this.recommandations = recommandations;
        this.type = type;
        this.datec = datec;
        this.consultations = consultations;
        this.ordonnancechirurgies = ordonnancechirurgies;
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }

    public BigDecimal getNumord() {
        return this.numord;
    }

    public void setNumord(BigDecimal numord) {
        this.numord = numord;
    }

    public String getRecommandations() {
        return this.recommandations;
    }

    public void setRecommandations(String recommandations) {
        this.recommandations = recommandations;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getDatec() {
        return this.datec;
    }

    public void setDatec(Date datec) {
        this.datec = datec;
    }

    public Set getConsultations() {
        return this.consultations;
    }

    public void setConsultations(Set consultations) {
        this.consultations = consultations;
    }

    public Set getOrdonnancechirurgies() {
        return this.ordonnancechirurgies;
    }

    public void setOrdonnancechirurgies(Set ordonnancechirurgies) {
        this.ordonnancechirurgies = ordonnancechirurgies;
    }

    public Set getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }

    public void setOrdonnancemedicamentses(Set ordonnancemedicamentses) {
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }

}
