package entite;
// Generated 16 avr. 2018 17:18:23 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Specialisationsalle generated by hbm2java
 */
public class Specialisationsalle implements java.io.Serializable {

    private SpecialisationsalleId id;
    private Salle salle;
    private Typechirurgie typechirurgie;
    private Date datec;
    private Set chirurgies = new HashSet(0);

    public Specialisationsalle() {
    }

    public Specialisationsalle(SpecialisationsalleId id, Salle salle, Typechirurgie typechirurgie, Date datec) {
        this.id = id;
        this.salle = salle;
        this.typechirurgie = typechirurgie;
        this.datec = datec;
    }

    public Specialisationsalle(SpecialisationsalleId id, Salle salle, Typechirurgie typechirurgie, Date datec, Set chirurgies) {
        this.id = id;
        this.salle = salle;
        this.typechirurgie = typechirurgie;
        this.datec = datec;
        this.chirurgies = chirurgies;
    }

    public SpecialisationsalleId getId() {
        return this.id;
    }

    public void setId(SpecialisationsalleId id) {
        this.id = id;
    }

    public Salle getSalle() {
        return this.salle;
    }

    public void setSalle(Salle salle) {
        this.salle = salle;
    }

    public Typechirurgie getTypechirurgie() {
        return this.typechirurgie;
    }

    public void setTypechirurgie(Typechirurgie typechirurgie) {
        this.typechirurgie = typechirurgie;
    }

    public Date getDatec() {
        return this.datec;
    }

    public void setDatec(Date datec) {
        this.datec = datec;
    }

    public Set getChirurgies() {
        return this.chirurgies;
    }

    public void setChirurgies(Set chirurgies) {
        this.chirurgies = chirurgies;
    }

}
