package entite;
// Generated 16 avr. 2018 17:18:23 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Typechirurgie generated by hbm2java
 */
public class Typechirurgie implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "salle_generator")
    @SequenceGenerator(name = "salle_generator", sequenceName = "SEQUENCE_TYPECHIR")
    @Column(name = "idtype", updatable = false, nullable = false, unique = true)
    private BigDecimal idtype;
    private String nom;
    private String description;
    private Set specialisationsalles = new HashSet(0);

    public Typechirurgie() {
    }

    public Typechirurgie(BigDecimal idtype, String nom) {
        this.idtype = idtype;
        this.nom = nom;
    }

    public Typechirurgie(String nom) {
        this.nom = nom;
    }

    public Typechirurgie(BigDecimal idtype, String nom, String description, Set specialisationsalles) {
        this.idtype = idtype;
        this.nom = nom;
        this.description = description;
        this.specialisationsalles = specialisationsalles;
    }

    public BigDecimal getIdtype() {
        return this.idtype;
    }

    public void setIdtype(BigDecimal idtype) {
        this.idtype = idtype;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getSpecialisationsalles() {
        return this.specialisationsalles;
    }

    public void setSpecialisationsalles(Set specialisationsalles) {
        this.specialisationsalles = specialisationsalles;
    }

}
